Dir {
  ArchiveDir ".";
};

BinDirectory "dists/blossom/main/binary-amd64" {
  Packages "dists/blossom/main/binary-amd64/Packages";
  Architectures "amd64";
}

BinDirectory "dists/blossom/main/binary-all" {
  Packages "dists/blossom/main/binary-all/Packages";
  Architectures "all";
}

TreeDefault {
  Directory "dists/blossom";
}

Default {
  Release {
    Suite "blossom";
    Codename "blossom";
    Components "main";
    Architectures "amd64 all";
  }
}